version: '3.0'

networks:
  database-frontend:
  
volumes:
  database-data:


services:
  database:
    image: postgres:13.5-alpine3.14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - database-frontend
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"

    depends_on:
      - database
    restart: on-failure
    networks:
      - database-frontend
